# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      dbnet:
        aliases:
          - "mongo"  
    secrets:
      - mongo-root-password             
      - mongo-root-username 
    ports:
      - 27017:27017
    volumes:
      - 'mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password

  mongo-express:
    image: mongo-express:local
    build:
          context: ./mongo-express
    container_name: mongo-express
    restart: always
    networks:
      dbnet:
        aliases:
          - "mongoexpress"
    secrets:
      - mongo-root-password 
      - mongo-root-username 
      - mongo-express-password 
      - mongo-express-username 
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: DOCKER-SECRET->mongo-root-username
      ME_CONFIG_MONGODB_ADMINPASSWORD: DOCKER-SECRET->mongo-root-password
      ME_CONFIG_BASICAUTH_PASSWORD: DOCKER-SECRET->mongo-express-password
      ME_CONFIG_BASICAUTH_USERNAME: DOCKER-SECRET->mongo-express-username
volumes:
  mongo:
    external: true

networks:
  dbnet:
    driver: bridge      

secrets:
  mongo-root-password:
    file: ${HOME}/.secrets/mongo-root-password
  mongo-root-username:
    file: ${HOME}/.secrets/mongo-root-username
  mongo-express-password:
    file: ${HOME}/.secrets/mongo-express-password
  mongo-express-username:
    file: ${HOME}/.secrets/mongo-express-username
